name: Build and Share APK

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Compress APK
        run: zip -r app-debug.txt app/build/outputs/apk/debug/app-debug.apk

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "APK Build - ${{ github.sha }}"
          body: "Please find attached the latest APK build. rename the extension from .txt to .zip. rename the extension for the security reasons."
          from: ashishbitto07@gmail.com
          to: ashishbitto07@gmail.com
          attachments: |
            app-debug.txt
          distribution: macos


