name: Building android library

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Analyze Android
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Mealz App
        uses: android-actions/setup-android@v2

      - name: Assemble
        run: |
          ./gradlew clean assembleRelease 
