name: Build and Share APK

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Compress APK
        run: zip -r app-release.zip app/build/outputs/apk/release/app-release.apk

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "APK Build - ${{ github.sha }}"
          body: "Please find attached the latest APK build."
          to: ashishbitto07@gmail.com
          attachments: |
            app-release.zip
          distribution: macos
